### ISSUE TITLE
Lucky Block Breaks in Water gets rid of custom name

### ISSUE THREAD

**Issue by NathanD2001** [Ghostriderdev/SuperLuckyBlock-Old#2]
When you place a lucky block in water and it breaks and it gives it back to you the lucky block is no longer named "Lucky Block" but it's named Luck's Head, the lucky block will still do it's purpose if it's placed as this but still I thought I'd report it :3

**Comment by Ghostriderdev** [comment]
Hello NathanD2001,
This is a minecraft mechanic and I am not sure if I can change this, but I will look in to it!

**Comment by Ghostriderdev** [comment]
Added in newest version!
Thanks for your suggestion. Also, I moved the repo to https://github.com/Ghostriderdev/SuperLuckyBlock(just for your info).
